Repository claudiodekker/laravel-auth, pull requests merged in 2023-07, with the labels that each got.

#54 Split up HTTP Traits into Mixins and Modifiers
  packages/bladebones/templates/Controllers/AccountRecoveryRequestController.bladetmpl
  packages/bladebones/templates/Controllers/Challenges/AccountRecoveryChallengeController.bladetmpl
  packages/bladebones/templates/Controllers/Challenges/MultiFactorChallengeController.bladetmpl
  packages/bladebones/templates/Controllers/Challenges/SudoModeChallengeController.bladetmpl
  packages/bladebones/templates/Controllers/LoginController.bladetmpl
  packages/bladebones/templates/Controllers/RegisterController.bladetmpl
  packages/bladebones/templates/Controllers/Settings/RegisterPublicKeyCredentialController.bladetmpl
  packages/bladebones/templates/Controllers/Settings/RegisterTotpCredentialController.bladetmpl
  packages/bladebones/tests/Feature/Console/GenerateCommandTest.php
  packages/core/src/Http/Controllers/Challenges/AccountRecoveryChallengeController.php
  packages/core/src/Http/Controllers/Challenges/MultiFactorChallengeController.php
  packages/core/src/Http/Controllers/Challenges/SudoModeChallengeController.php
  packages/core/src/Http/Controllers/LoginController.php
  packages/core/src/Http/Controllers/RegisterController.php
  packages/core/src/Http/Controllers/Settings/RegisterPublicKeyCredentialController.php
  packages/core/src/Http/Controllers/Settings/RegisterTotpCredentialController.php
  packages/core/src/Http/Mixins/Challenges/PasswordChallenge.php
  packages/core/src/Http/Mixins/Challenges/PublicKeyChallenge.php
  packages/core/src/Http/Mixins/Challenges/TotpChallenge.php
  packages/core/src/Http/Mixins/EnablesSudoMode.php
  packages/core/src/Http/Modifiers/EmailBased.php
  packages/core/src/Http/Modifiers/UsernameBased.php
  packages/core/src/Http/Modifiers/WithoutRateLimiting.php
  packages/core/src/Http/Modifiers/WithoutVerificationEmail.php
Labels: change

#55 Add Timebox (prevent timeless timing attack vulnerability)
  packages/bladebones/templates/Tests/AuthenticationTest.bladetmpl
  packages/bladebones/tests/Feature/Console/GenerateCommandTest.php
  packages/core/src/Http/Concerns/Login/PasskeyBasedAuthentication.php
  packages/core/src/Http/Concerns/Login/PasswordBasedAuthentication.php
  packages/core/src/Http/Concerns/Registration/PasskeyBasedRegistration.php
  packages/core/src/Http/Concerns/Registration/PasswordBasedRegistration.php
  packages/core/src/Http/Controllers/AccountRecoveryRequestController.php
  packages/core/src/Http/Controllers/Challenges/AccountRecoveryChallengeController.php
  packages/core/src/Http/Controllers/Challenges/MultiFactorChallengeController.php
  packages/core/src/Http/Controllers/Challenges/SudoModeChallengeController.php
  packages/core/src/Http/Mixins/Challenges/PasswordChallenge.php
  packages/core/src/Http/Mixins/Challenges/PublicKeyChallenge.php
  packages/core/src/Http/Mixins/Challenges/TotpChallenge.php
  packages/core/src/Testing/EmailVerification/RegisterWithVerificationEmailTests.php
  packages/core/src/Testing/EmailVerification/RegisterWithoutVerificationEmailTests.php
  packages/core/src/Testing/Helpers.php
  packages/core/src/Testing/Partials/CancelPasskeyBasedRegistrationTests.php
  packages/core/src/Testing/Partials/Challenges/MultiFactor/SubmitMultiFactorChallengeUsingPublicKeyCredentialTests.php
  packages/core/src/Testing/Partials/Challenges/MultiFactor/SubmitMultiFactorChallengeUsingTotpCodeTests.php
  packages/core/src/Testing/Partials/Challenges/MultiFactor/ViewMultiFactorChallengePageTests.php
  packages/core/src/Testing/Partials/Challenges/Recovery/SubmitAccountRecoveryChallengeTests.php
  packages/core/src/Testing/Partials/Challenges/Recovery/ViewAccountRecoveryChallengePageTests.php
  packages/core/src/Testing/Partials/Challenges/SudoMode/ConfirmSudoModeUsingCredentialTests.php
  packages/core/src/Testing/Partials/Challenges/SudoMode/ConfirmSudoModeUsingPasswordTests.php
  packages/core/src/Testing/Partials/Challenges/SudoMode/ViewSudoModeChallengePageTests.php
  packages/core/src/Testing/Partials/RateLimiting/AccountRecoveryChallengeRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/AccountRecoveryChallengeWithoutRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/AccountRecoveryRequestRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/AccountRecoveryRequestWithoutRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/LoginRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/LoginWithoutRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/MultiFactorChallengeRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/MultiFactorChallengeWithoutRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/SudoModeRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/SudoModeWithoutRateLimitingTests.php
  packages/core/src/Testing/Partials/SubmitAccountRecoveryRequestTests.php
  packages/core/src/Testing/Partials/SubmitPasskeyBasedAuthenticationTests.php
  packages/core/src/Testing/Partials/SubmitPasskeyBasedRegistrationTests.php
  packages/core/src/Testing/Partials/SubmitPasswordBasedAuthenticationTests.php
  packages/core/src/Testing/Partials/SubmitPasswordBasedRegistrationTests.php
  packages/core/src/Testing/Support/InstantlyResolvingTimebox.php
Labels: enhancement

#56 Bladebones: Clean up routes file & de-duplicate named routes
  packages/bladebones/src/Testing/Partials/MultiFactorChallengeViewTests.php
  packages/bladebones/stubs/defaults/routes/web.stub
  packages/bladebones/stubs/defaults/views/challenges/multi_factor.blade.stub
  packages/bladebones/stubs/defaults/views/settings/confirm_public_key.blade.stub
  packages/bladebones/stubs/defaults/views/settings/confirm_recovery_codes.blade.stub
  packages/bladebones/templates/Controllers/LoginController.bladetmpl
  packages/core/src/Testing/Helpers.php
  packages/core/src/Testing/Partials/Challenges/MultiFactor/SubmitMultiFactorChallengeTests.php
  packages/core/src/Testing/Partials/Challenges/MultiFactor/SubmitMultiFactorChallengeUsingPublicKeyCredentialTests.php
  packages/core/src/Testing/Partials/Challenges/MultiFactor/SubmitMultiFactorChallengeUsingTotpCodeTests.php
  packages/core/src/Testing/Partials/Challenges/MultiFactor/ViewMultiFactorChallengePageTests.php
  packages/core/src/Testing/Partials/RateLimiting/MultiFactorChallengeRateLimitingTests.php
  packages/core/src/Testing/Partials/RateLimiting/MultiFactorChallengeWithoutRateLimitingTests.php
  packages/core/src/Testing/Partials/Settings/PublicKey/ConfirmPublicKeyCredentialRegistrationTests.php
  packages/core/src/Testing/Partials/Settings/Recovery/ConfirmRecoveryCodesGenerationTests.php
  packages/core/src/Testing/Partials/Settings/Totp/CancelTotpCredentialRegistrationTests.php
  packages/core/src/Testing/Partials/Settings/Totp/ConfirmTotpCredentialRegistrationTests.php
  packages/core/src/Testing/Partials/SubmitPasswordBasedAuthenticationTests.php
Labels: change

#58 Update descriptions
  README.md
  composer.json
  packages/core/composer.json
Labels: documentation

#59 UserFactory: Use `fake()` helper instead of `$this->faker`
  packages/core/templates/Database/UserFactory.bladetmpl
Labels: optimization
